### ISSUE TITLE
Refreshing page makes App loose it's state.

### ISSUE THREAD

**Issue by vincentvanhees** [habitus-eu/HabitusGUI#54]
When refreshing page with HABITUS2.0-dev on UCloud the app restarts en looses its state.
Investigate whether this can be resolved from within HabitusGUI.

Update: Is being addressed with nohup argument, see #60.

Follow-up step:

- [ ] Also modify Shiny code to remember its own state (tick boxes ticked, paths specified, etc...) after been rephreshed.

**Comment by jhmigueles** [comment]
Hi @vincentvanhees, I have written some code with a proposal for this [here](https://github.com/jhmigueles/HabitusGUI/tree/issue54_app_status/R#:~:text=dummyApp2_save%20load%20buttons.R).

The dummyApp2_save load buttons.R script includes a shiny app in which you can save/load the options selected (even the file uploaded) to the app. Let me know what you think about this option for HABITUS.

**Comment by vincentvanhees** [comment]
Looks good @jhmigueles 

To minimize the number of buttons in the HabitusGUI app. How about implementing it in HabitusGUI as follows?
- Auto-save when user goes to next page. For this see `observeEvent(input$page_...` in myApp where we already do various checks before goin to the next page. Saving the state could be one of them. As a result, we do not need a "Save" button.
- The "load" button could then be on each page, but we can name it "Undo" because clicking it will reset the state of the page to the last saved state, which was when we arrived at the page.

**Comment by jhmigueles** [comment]
Thanks @vincentvanhees 

I've made some progress here. The app is able to save the state of most of the input and this is done when going to the next page as you suggested. The app is also able to save the directories selected in previous runs (for now I have only implemented this for the rawaccdir. But I'm finding some challenges:

1. The conditional panel about the researchgoals get updated when it is generated, so I cannot save the state of it, because everything gets unselected every time the app is run. This is not a major problem for the functioning of the app but the user would miss the proposed pipeline suggestion.
2. The selected directories are saved and used, but the shinyDirButton would not show the selected directory from a previous run. For this, I have included some text to show up that a directory is selected even if not shown in the button:
![image](https://user-images.githubusercontent.com/28734336/230329268-4ec32015-41f9-4acc-9766-be143129698f.png)
3. After selecting everything, I cannot make GGIR work, I see some warning messages and the output is not generated, but I'm not sure if I'm doing something wrong or this is to be expected. Here what I see in the console:
![image](https://user-images.githubusercontent.com/28734336/230329815-6d62fed4-fa39-4e2e-90a0-6dc7b0b899c1.png)

**Comment by vincentvanhees** [comment]
> 1. The conditional panel about the researchgoals get updated when it is generated, so I cannot save the state of it, because everything gets unselected every time the app is run. This is not a major problem for the functioning of the app but the user would miss the proposed pipeline suggestion.

Can you make it in such a way that when previously stored state is loaded the app also triggers the re-[generation of the proposed pipeline](https://github.com/habitus-eu/HabitusGUI/blob/main/R/myApp.R#L418-L422). Maybe via an observeEvent?

> 2. The selected directories are saved and used, but the shinyDirButton would not show the selected directory from a previous run. For this, I have included some text to show up that a directory is selected even if not shown in the button:

Did this work in the dummy app? If not, maybe first try to figure out how we can get it to work there?

> 3. After selecting everything, I cannot make GGIR work, I see some warning messages and the output is not generated, but I'm not sure if I'm doing something wrong or this is to be expected. Here what I see in the console:

This reminds me now that the app only works in Linux following the changes I made in December, because I had to include those steps for it to work in UCloud. Maybe it is easier if I try to work on a solution for this as I agree that it would be nice if we could get it to also work in Windows even if it is just for testing purposes.

**Comment by jhmigueles** [comment]
> Can you make it in such a way that when previously stored state is loaded the app also triggers the re-[generation of the proposed pipeline](https://github.com/habitus-eu/HabitusGUI/blob/main/R/myApp.R#L418-L422). Maybe via an observeEvent?

This is fixed now, the app remembers and uses the researchgoals selected in previous runs.

> Did this work in the dummy app? If not, maybe first try to figure out how we can get it to work there?

I have been trying this, but there is no way to modify the shinyDirButton to show the path from previous run, so that's why I included the message right below as you can see in the image above. In the dummy app I used fileInput but did not include any directory selection button. Note this is not a problem for the app, the app uses the directory from previous runs as it is supposed to (and the user can always see the directory selected).

----

I'm wondering what to do with the config file, should the app load the config file from a previous run or always require the user to upload a config file? What do you think?

**Comment by vincentvanhees** [comment]
Just recap from our meeting:
- Saving/loading of state sounds good, please do for all directories and file paths.
- We keep forcing user to upload and specify config file, we do not want software to start proposing defaults because the config file is the only step in the App where the user is asked to specify what needs to be done. Skipping this step would almost certainly result in bad output.
