### ISSUE TITLE
Error running analyses in Habitus v1.9.6 from UCloud - permission denied 

### ISSUE THREAD

**Issue by TeunRemmers** [habitus-eu/HabitusGUI#55]
From my Home-Folder in UCloud, @vincentvanhees and myself tried to run several test-analyses in Habitus v.1.9.6. I'm getting an error "Permission denied" when running my test accelerometer and GPS data in UCloud. No results are processed in the UCloud Jobs folder. 

Jasper tested the exact same data in the same Habitus version and it worked fine for him, so he asked us to repeat the analyses in Habitus with the excact same job-parameters in a .json file. Still, we are experiencing the same errors as before ("permission denied").

@emolinaro, can you help us with this problem? If it helps for you we can also share our data within UCloud... please let us know if you want us to also share this with you.

[stdout.txt](https://github.com/habitus-eu/HabitusGUI/files/9019439/stdout.txt)
[stdout-2.txt](https://github.com/habitus-eu/HabitusGUI/files/9019443/stdout-2.txt)
[Testdata 01042022.zip](https://github.com/habitus-eu/HabitusGUI/files/9019464/Testdata.01042022.zip)
[TestJasper.zip](https://github.com/habitus-eu/HabitusGUI/files/9019478/TestJasper.zip)

**Comment by emolinaro** [comment]
@TeunRemmers this error happens when the input files are owned by `root`. 

You should change the files ownership by launching another app, for example Terminal Ubuntu. You have to mount the data folder within this app instance and run the following command from the corresponding terminal interface:

`sudo chown -R ucloud:ucloud /work/my_input_data_folder`

Notice that `sudo` doesn't work within the HABITUS app. That's why you should use the app mentioned above.

**Comment by vincentvanhees** [comment]
When I tested it, I did not use the 'Select folders to use' section.
I think you only need this if you plan to work with data that is spread out over locations within UCloud. So, I think you can skip this for now.

**Comment by vincentvanhees** [comment]
This indicates that you cannot use sudo, try again without sudo: `chown -R ucloud:ucloud /work/TestJasper`

**Comment by TeunRemmers** [comment]
The "chown" command seems to work...
![Screenshot 2022-07-12 at 11 30 57](https://user-images.githubusercontent.com/102030034/178459574-e16a8fe3-4927-4463-b48a-23ccfe2cc9d8.png)

... but I'm still experiencing the same error in PalmsPy interface
![Screenshot 2022-07-12 at 11 32 23](https://user-images.githubusercontent.com/102030034/178459462-80fab7d3-d7f3-44fe-90d0-a5bd3c2befd5.png)

**Comment by vincentvanhees** [comment]
This is not an error, but a warning. Please wait for the analyses to finish.

**Comment by TeunRemmers** [comment]
Thanks for the help Vincent, shortly (1-2 minutes) after the warning the server disconnects (see screenshot above). When I try to examine the results in the specified folder, no results exist. I also attached the config .json file and the log of Palmspy analyses.

[PALMSpy.log](https://github.com/habitus-eu/HabitusGUI/files/9091981/PALMSpy.log)
[config.json.zip](https://github.com/habitus-eu/HabitusGUI/files/9091990/config.json.zip)

**Comment by emolinaro** [comment]
@TeunRemmers does the PALMSpy log file in `/work` report some information?

**Comment by TeunRemmers** [comment]
@emolinaro what do you mean with the PALMSpy log in /work? I only have the folders beneath. Where can I find /work?
![Screenshot 2022-07-12 at 12 40 58](https://user-images.githubusercontent.com/102030034/178472609-c3ce2ecf-c949-4177-bbe9-24f41a4f3383.png)

 If you refer to the Jobs-folder, this does not include any PALMSpy log file (see beneath).
![Screenshot 2022-07-12 at 12 42 37](https://user-images.githubusercontent.com/102030034/178472821-3c78aa83-34a9-4671-bfbe-e731b6f5b276.png)

**Comment by emolinaro** [comment]
The HABITUS app should produce a log file in `/work` when the run is completed. It seems that the analysis was not completed when you closed the job.

**Comment by vincentvanhees** [comment]
Teun: `/work` is the folder you mounted when you started the app. From within the app this is called `/work` but from your own perspective it is probably something else. For example last week you shared this screen shot:

>
> 
> ![Screenshot 2022-07-06 at 11 18 33](https://user-images.githubusercontent.com/102030034/177516491-fa905ab9-68db-4e18-a318-69378e1b1249.png)


which would mean that your work for that run was `/Home/TestJasper/Test01042022/data`

**Comment by TeunRemmers** [comment]
@emolinaro thank you for you answer, I never changed the permissions of the folders. Now I tried to run the same analyses in the project "Skilfull Start" workspace. However from this workspace, I do not have access to Habitus v2.0-def but only Shiny v4.2.0. When I try to open the terminal in Shiny for subsequent PALMSpy analyses, I see the following screen (not the familiair terminal window) where you can specify PALMSpy / GGIR, etc. 

<img width="242" alt="Screenshot 2022-07-12 at 14 32 33" src="https://user-images.githubusercontent.com/102030034/178491297-6880e59f-b25b-44ce-844c-fb1b3310bdea.png">

**Comment by emolinaro** [comment]
Hi, you should not use the Shiny app anymore.  The script used to launch HABITUS in this app changes the folder permissions. You should use instead the app HABITUS v2.0-dev. Please, do the tests using the project "HABITUS development and testing". @vincentvanhees  can you add him to the project and then to the group "test_plamsplusr"? .

**Comment by vincentvanhees** [comment]
@TeunRemmers let me know when you have accepted the invitation for the project, because I then als need to add you to a group "test_palmsplusr". I cannot do that before you have accepted the first invitation.

**Comment by TeunRemmers** [comment]
@vincentvanhees I accepted the invitation.

**Comment by vincentvanhees** [comment]
Thanks, I have now also added you to the specific group. This is the group Emiliano and I used to test the app.

**Comment by TeunRemmers** [comment]
I've tested the data again in the new Shared data folder and I've made a little screen recording following all my steps so that you can maybe see what I'm doing wrong. You can also use the data in the Folder "Test01042022" to test if you can run my data successfully.

https://user-images.githubusercontent.com/102030034/178713516-cfa627d4-0fa5-457e-9c9c-7fc90f57e7f9.mp4

**Comment by vincentvanhees** [comment]
Thanks @TeunRemmers for recording the video.

In the log file I see:

`Caused by: java.io.FileNotFoundException: /work/Test01042022/data/acc/1221_Fontys_80.csv (Permission denied)`
`java.io.FileNotFoundException: /work/Test01042022/data/acc/1221_Fontys_80.csv (Permission denied)`


So, I then use the Ubuntu Terminal app and cd to the data folder I see:

![image](https://user-images.githubusercontent.com/8362333/178957642-507b7148-e997-4589-acaf-c382b36876e9.png)

this indicates that the folders are owned by user ucloud, but not the files which are still owned by root.

When I then try to chown everything in the data folder without sudo, it does not allow me:
![image](https://user-images.githubusercontent.com/8362333/178958000-8ac14732-e272-40ca-b855-e448e87d6941.png)

but when I use sudo it allows me to do this:
![image](https://user-images.githubusercontent.com/8362333/178958126-cd878599-e00f-4263-917a-cda75457f94d.png)

the ownership has now changed from root to ucloud.

When I then re-run the Habitus 2.0-dev app, I see in the log file (via the terminal) that the problem is again with the Window sizes as we previously discussed with Jasper:

![image](https://user-images.githubusercontent.com/8362333/178959142-4ab478ae-0bba-4021-8c44-10876dea1e84.png)

This looks like a problem with either the data, the config file or PALMSpy itself. To understand whether the Habitus 2.0-dev app plays a role in it,  you may want to process the file again with Habitus 1.9-6.

For some reason the Habitus 2.0-dev app crashes, which I think is a separate issue.
