### ISSUE TITLE
Path to conda executable must be general

### ISSUE THREAD

**Issue by emolinaro** [habitus-eu/HabitusGUI#68]
https://github.com/habitus-eu/HabitusGUI/blob/9092df1a1b6ecc028b29dc82239e894f85c5c54e/R/PALMSpyshiny.R#L13

**Comment by vincentvanhees** [comment]
This line is correct, because it is only supposed to be used by me to test the app locally.
The line that should run on UCloud is when username is 'shiny' or 'ucloud' is: https://github.com/habitus-eu/HabitusGUI/blob/9092df1a1b6ecc028b29dc82239e894f85c5c54e/R/PALMSpyshiny.R#L16

That line is consistent with what we had before except the addition of the unbuffer argument as I explained in my e-mail. To use the unbuffer argument we will need to add expect to the dependencies as I mentioned in my e-mail.

Note that there is an open issue for making the hard-coded path on line 13 more generic: https://github.com/habitus-eu/HabitusGUI/issues/66 However, this should not affect usage on UCloud as the line is not intended for UCloud.

**Comment by emolinaro** [comment]
Ok, there is no problem when launching the app from UCloud. I close this issue.
